# Generated by Django 3.1.5 on 2021-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogVlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='blog_vlog', verbose_name='Product Image')),
                ('description', models.TextField(max_length=1000)),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'blog_vlog',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='destination', verbose_name='Product Image')),
                ('description', models.TextField(max_length=1000)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='highlights', verbose_name='Product Image')),
                ('description', models.TextField(max_length=1000)),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'highlights',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'testimonials',
            },
        ),
        migrations.CreateModel(
            name='TourExpiriance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_type', models.CharField(choices=[('History', 'History'), ('Myth or Reality', 'Myth or Reality'), ('Travel Stories', 'Travel Stories'), ('Traditions', 'Traditions')], max_length=20)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='tour_expiriance', verbose_name='Product Image')),
                ('description', models.TextField(max_length=1000)),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'tour_expiriance',
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_type', models.CharField(choices=[('Ethnography', 'Ethnography'), ('Photography', 'Photography'), ('History', 'History'), ('Bird Watching', 'Bird Watching'), ('Hiking', 'Hiking'), ('Sight Seeing', 'Sight Seeing'), ('Cultural', 'Cultural')], max_length=20)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='tour_package', verbose_name='Product Image')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
            options={
                'db_table': 'tour_package',
            },
        ),
    ]
